# Generated by Django 5.2.17 on 2026-09-07 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razón social')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('nombre_contacto', models.CharField(blank=True, max_length=120, verbose_name='persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=150, verbose_name='correo')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('dias_credito', models.IntegerField(default=0, help_text='0 = paga de contado.', verbose_name='días de crédito')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: sus pedidos históricos lo siguen referenciando.', verbose_name='activo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_distribucion', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'cliente de distribución',
                'verbose_name_plural': 'clientes de distribución',
                'db_table': 'clientes_distribucion',
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'nit'), name='cliente_distribucion_nit_unico_por_negocio', violation_error_message='Ya hay un cliente con ese NIT en este negocio.'), models.CheckConstraint(condition=models.Q(('dias_credito__gte', 0)), name='cliente_distribucion_credito_no_negativo', violation_error_message='Los días de crédito no pueden ser negativos.')],
            },
        ),
    ]
