# Generated by Django 5.2.17 on 2026-09-08 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_crear_catalogo'),
        ('distribucion', '0001_crear_clientes_distribucion'),
        ('negocios', '0001_crear_negocios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo lo pidió la tienda. Desde aquí corre el plazo de crédito.', verbose_name='fecha del pedido')),
                ('fecha_entrega', models.DateTimeField(blank=True, help_text='Vacío mientras el pedido no se haya entregado.', null=True, verbose_name='fecha de entrega')),
                ('cliente_distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='distribucion.clientedistribucion', verbose_name='cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_distribucion', to='negocios.negocio', verbose_name='negocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_distribucion', to=settings.AUTH_USER_MODEL, verbose_name='tomado por')),
            ],
            options={
                'verbose_name': 'pedido de distribución',
                'verbose_name_plural': 'pedidos de distribución',
                'db_table': 'pedidos_distribucion',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Foto del precio mayorista al momento de vender, no el precio de hoy.', max_digits=12, verbose_name='precio unitario')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido_distribucion', to='negocios.negocio', verbose_name='negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido_distribucion', to='catalogo.producto', verbose_name='producto')),
                ('pedido_distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='distribucion.pedidodistribucion', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'detalle de pedido de distribución',
                'verbose_name_plural': 'detalles de pedido de distribución',
                'db_table': 'detalle_pedido_distribucion',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedidodistribucion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_entrega__isnull', True), ('fecha_entrega__gte', models.F('fecha_pedido')), _connector='OR'), name='pedido_distribucion_fechas_coherentes', violation_error_message='Un pedido no puede entregarse antes de haberse pedido.'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidodistribucion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_distribucion_cantidad_positiva', violation_error_message='La cantidad debe ser mayor que cero.'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidodistribucion',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_distribucion_precio_no_negativo', violation_error_message='El precio no puede ser negativo.'),
        ),
    ]
