# Generated by Django 5.2.17 on 2026-09-08 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0002_crear_pedidos_distribucion'),
        ('negocios', '0001_crear_negocios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='transferencia', max_length=20, verbose_name='método de pago')),
                ('referencia_transaccion', models.CharField(blank=True, help_text='Número de comprobante o de consignación. Vacío en los pagos en efectivo.', max_length=100, verbose_name='referencia de la transacción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo se recibió el dinero, que no siempre es cuándo se registró.', verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'pago de distribución',
                'verbose_name_plural': 'pagos de distribución',
                'db_table': 'pagos_distribucion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='pedidodistribucion',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, help_text='Por qué no se pudo entregar. Obligatorio en el estado «no entregado».', verbose_name='motivo de la no entrega'),
        ),
        migrations.AlterField(
            model_name='pedidodistribucion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.AddConstraint(
            model_name='pedidodistribucion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'no_entregado'), _negated=True), models.Q(('motivo_no_entrega', ''), _negated=True), _connector='OR'), name='pedido_distribucion_no_entregado_con_motivo', violation_error_message='Hay que decir por qué no se pudo entregar.'),
        ),
        migrations.AddField(
            model_name='pagodistribucion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_distribucion', to='negocios.negocio', verbose_name='negocio'),
        ),
        migrations.AddField(
            model_name='pagodistribucion',
            name='pedido_distribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='distribucion.pedidodistribucion', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='pagodistribucion',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_distribucion_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='recibido por'),
        ),
        migrations.AddConstraint(
            model_name='pagodistribucion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_distribucion_monto_positivo', violation_error_message='El monto de un pago debe ser mayor que cero.'),
        ),
    ]
