# Generated by Django 5.2.17 on 2026-09-07 00:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula de ciudadanía'), ('cedula_extranjeria', 'Cédula de extranjería'), ('pasaporte', 'Pasaporte'), ('tarjeta_identidad', 'Tarjeta de identidad')], default='cedula', max_length=25, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(max_length=30, verbose_name='número de documento')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=120, verbose_name='apellido')),
                ('fecha_nacimiento', models.DateField(help_text='Se guarda la fecha y no la edad: la edad cambia sola cada año.', verbose_name='fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=150, verbose_name='correo')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: sus cuentas y pedidos lo siguen referenciando.', verbose_name='activo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'ordering': ['apellido', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'tipo_documento', 'numero_documento'), name='cliente_documento_unico_por_negocio', violation_error_message='Ya hay un cliente con ese documento en este negocio.'), models.CheckConstraint(condition=models.Q(('fecha_nacimiento__gt', datetime.date(1900, 1, 1))), name='cliente_fecha_nacimiento_razonable', violation_error_message='La fecha de nacimiento no es una fecha válida.')],
            },
        ),
    ]
