# Generated by Django 5.2.17 on 2026-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_crear_clientes'),
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['negocio', 'apellido', 'nombre'], name='cliente_negocio_nombre_idx'),
        ),
    ]
