export const PROVEEDORES_DE_EJEMPLO = [
  {
    id: 'ejemplo-bavaria',
    razonSocial: 'Bavaria S.A.',
    nit: 'NIT pendiente',
    nombreContacto: 'Sin asignar',
    telefono: '',
    correo: '',
    ciudad: '',
    direccion: '',
    cantidadProductos: 0,
  },
  {
    id: 'ejemplo-postobon',
    razonSocial: 'Postobón S.A.',
    nit: 'NIT pendiente',
    nombreContacto: 'Sin asignar',
    telefono: '',
    correo: '',
    ciudad: '',
    direccion: '',
    cantidadProductos: 0,
  },
  {
    id: 'ejemplo-coca-cola',
    razonSocial: 'Coca-Cola FEMSA',
    nit: 'NIT pendiente',
    nombreContacto: 'Sin asignar',
    telefono: '',
    correo: '',
    ciudad: '',
    direccion: '',
    cantidadProductos: 0,
  },
]