export const CLIENTES_DE_EJEMPLO = [
  {
    id: 'cliente-carlos',
    nombre: 'Carlos Ramírez',
    telefono: '300 555 1234',
    tipo: 'persona',
    tipoDocumento: 'Cédula',
    documento: '1.045.300.123',
    fechaNacimiento: '1992-04-18',
    correo: 'carlos@example.com',
    ciudad: 'Bogotá',
    saldoPendiente: 0,
  },
  {
    id: 'cliente-maria',
    nombre: 'María Gómez',
    telefono: '311 222 8890',
    tipo: 'persona',
    tipoDocumento: 'Cédula',
    documento: '52.418.670',
    fechaNacimiento: '1988-09-02',
    correo: 'maria@example.com',
    ciudad: 'Medellín',
    saldoPendiente: 80000,
  },
  {
    id: 'cliente-taller-el-rayo',
    nombre: 'Taller El Rayo',
    telefono: '320 444 1100',
    tipo: 'establecimiento',
    documento: '901.245.880-1',
    segmento: 'Tienda',
    contacto: 'Pedro Niño',
    correo: 'compras@elrayo.example',
    ciudad: 'Cali',
    saldoPendiente: 250000,
  },
  {
    id: 'cliente-andres',
    nombre: 'Andrés Patiño',
    telefono: '301 678 9012',
    tipo: 'persona',
    tipoDocumento: 'Cédula',
    documento: '1.018.774.290',
    fechaNacimiento: '1996-01-27',
    correo: '',
    ciudad: 'Cali',
    saldoPendiente: 7000,
  },
  {
    id: 'cliente-diana',
    nombre: 'Diana Cardona',
    telefono: '315 333 7766',
    tipo: 'persona',
    tipoDocumento: 'Cédula',
    documento: '43.900.126',
    fechaNacimiento: '1990-06-11',
    correo: '',
    ciudad: 'Bogotá',
    saldoPendiente: 0,
  },
  {
    id: 'cliente-moto-express',
    nombre: 'Moto Express SAS',
    telefono: '318 901 2345',
    tipo: 'establecimiento',
    documento: '900.776.552-3',
    segmento: 'Distribuidor',
    contacto: 'Laura Vega',
    correo: 'pedidos@motoexpress.example',
    ciudad: 'Medellín',
    saldoPendiente: 0,
  },
]