# Generated by Django 5.2.17 on 2026-09-03 02:59

import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=120, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('rol', models.CharField(blank=True, choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero')], max_length=20, verbose_name='rol')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: borrar rompe la trazabilidad.', verbose_name='activo')),
                ('es_staff', models.BooleanField(default=False, verbose_name='accede al admin de Django')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('negocio', models.ForeignKey(blank=True, help_text='Vacío solo para el staff de la plataforma.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='negocios.negocio', verbose_name='negocio')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre', 'apellido'],
            },
            managers=[
                ('objects', usuarios.models.GestorDeUsuarios()),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('correo', models.EmailField(max_length=150, verbose_name='correo invitado')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero')], max_length=20, verbose_name='rol')),
                ('hash_token', models.CharField(max_length=64, unique=True, verbose_name='hash del token')),
                ('expira_en', models.DateTimeField(verbose_name='expira en')),
                ('aceptada_en', models.DateTimeField(blank=True, null=True, verbose_name='aceptada en')),
                ('aceptada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_aceptada', to=settings.AUTH_USER_MODEL, verbose_name='aceptada por')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='invitada por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', True), models.Q(('negocio__isnull', False), models.Q(('rol', ''), _negated=True)), _connector='OR'), name='usuario_requiere_negocio_y_rol', violation_error_message='Todo usuario debe pertenecer a un negocio y tener un rol, salvo el staff de la plataforma.'),
        ),
        migrations.AddConstraint(
            model_name='invitacion',
            constraint=models.UniqueConstraint(condition=models.Q(('aceptada_en__isnull', True)), fields=('negocio', 'correo'), name='invitacion_pendiente_unica_por_correo', violation_error_message='Ya hay una invitación pendiente para ese correo.'),
        ),
    ]
