# Generated by Django 5.2.17 on 2026-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='usuarios_grupos', help_text='Grupos a los que pertenece; hereda los permisos de cada uno.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='usuarios_permisos', help_text='Permisos concedidos directamente a este usuario.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='permisos del usuario'),
        ),
        migrations.AlterModelTable(
            name='invitacion',
            table='invitaciones',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
