# Generated by Django 5.2.17 on 2026-09-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0002_renombrar_tabla_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: los productos históricos la siguen usando.', verbose_name='activa')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('sku', models.CharField(db_index=True, max_length=50, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('costo', models.DecimalField(decimal_places=2, default=0, help_text='Costo de referencia con el que se calcula el margen. Lo que cobra cada proveedor va en productos_proveedores.', max_digits=12, verbose_name='costo')),
                ('precio_evento', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio en evento')),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio mayorista')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: los pedidos históricos lo siguen referenciando.', verbose_name='activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razón social')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('nombre_contacto', models.CharField(blank=True, max_length=120, verbose_name='persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=150, verbose_name='correo')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: las compras pasadas lo siguen referenciando.', verbose_name='activo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio de compra')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Referencia con la que el proveedor identifica el producto en su catálogo.', max_length=50, verbose_name='código del proveedor')),
                ('es_principal', models.BooleanField(default=False, help_text='Solo uno por producto: al que se le compra por defecto.', verbose_name='es el proveedor habitual')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_proveedores', to='negocios.negocio', verbose_name='negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_de_proveedor', to='catalogo.producto', verbose_name='producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_de_producto', to='catalogo.proveedor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'producto por proveedor',
                'verbose_name_plural': 'productos por proveedor',
                'db_table': 'productos_proveedores',
                'ordering': ['producto', '-es_principal', 'precio_compra'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='productos', through='catalogo.ProductoProveedor', to='catalogo.proveedor', verbose_name='proveedores'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='categoria_nombre_unico_por_negocio', violation_error_message='Ya existe una categoría con ese nombre en este negocio.'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('nit', ''), _negated=True), fields=('negocio', 'nit'), name='proveedor_nit_unico_por_negocio', violation_error_message='Ya hay un proveedor con ese NIT en este negocio.'),
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='producto_proveedor_sin_repetir', violation_error_message='Ese proveedor ya está registrado para este producto.'),
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('producto',), name='producto_con_un_solo_proveedor_principal', violation_error_message='El producto ya tiene un proveedor habitual.'),
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('precio_compra__gte', 0)), name='producto_proveedor_precio_no_negativo', violation_error_message='El precio de compra no puede ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('negocio', 'sku'), name='producto_sku_unico_por_negocio', violation_error_message='Ya existe un producto con ese SKU en este negocio.'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('costo__gte', 0), ('precio_evento__gte', 0), ('precio_mayorista__gte', 0)), name='producto_precios_no_negativos', violation_error_message='Ni el costo ni los precios pueden ser negativos.'),
        ),
    ]
