# Generated by Django 5.2.17 on 2026-09-07 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_crear_catalogo'),
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('bodega', 'Bodega'), ('punto_venta_evento', 'Punto de venta en evento')], default='bodega', max_length=30, verbose_name='tipo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar en vez de borrar: el kardex histórico la sigue referenciando.', verbose_name='activa')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'db_table': 'ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, help_text='Saldo cacheado del kardex. La fuente de verdad es movimientos_inventario.', max_digits=12, verbose_name='cantidad disponible')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='negocios.negocio', verbose_name='negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='catalogo.producto', verbose_name='producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.ubicacion', verbose_name='ubicación')),
            ],
            options={
                'verbose_name': 'existencia',
                'verbose_name_plural': 'existencias',
                'db_table': 'existencias',
                'ordering': ['ubicacion', 'producto'],
            },
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='ubicacion_nombre_unico_por_negocio', violation_error_message='Ya existe una ubicación con ese nombre en este negocio.'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.UniqueConstraint(fields=('producto', 'ubicacion'), name='existencia_unica_por_producto_y_ubicacion', violation_error_message='Ese producto ya tiene existencias en esta ubicación.'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='existencia_no_negativa', violation_error_message='Las existencias no pueden quedar en negativo.'),
        ),
    ]
