# Generated by Django 5.2.17 on 2026-09-07 00:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_crear_catalogo'),
        ('inventario', '0001_crear_ubicaciones_y_existencias'),
        ('negocios', '0001_crear_negocios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('traslado', 'Traslado'), ('ajuste', 'Ajuste'), ('merma', 'Merma')], max_length=20, verbose_name='tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Con signo: positiva suma al inventario, negativa resta. Nunca cero.', max_digits=12, verbose_name='cantidad')),
                ('referencia_tipo', models.CharField(choices=[('pedido_evento', 'Pedido de evento'), ('pedido_distribucion', 'Pedido de distribución'), ('compra', 'Compra a proveedor'), ('traslado', 'Traslado entre ubicaciones'), ('ajuste', 'Ajuste manual')], help_text='Qué originó el movimiento.', max_length=30, verbose_name='tipo de referencia')),
                ('referencia_id', models.BigIntegerField(blank=True, help_text='Id dentro de la tabla que indica referencia_tipo. Vacío en un ajuste manual.', null=True, verbose_name='id de la referencia')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo ocurrió el movimiento, que no siempre es cuándo se registró.', verbose_name='fecha')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='negocios.negocio', verbose_name='negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.producto', verbose_name='producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.ubicacion', verbose_name='ubicación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='movimiento_producto_fecha_idx'), models.Index(fields=['referencia_tipo', 'referencia_id'], name='movimiento_referencia_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='movimiento_cantidad_distinta_de_cero', violation_error_message='Un movimiento de cero no es un movimiento.')],
            },
        ),
    ]
