# Generated by Django 5.2.17 on 2026-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_crear_catalogo'),
        ('inventario', '0002_crear_movimientos_inventario'),
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Por debajo de esto hay que reponer. 0 = sin alerta, no «alerta siempre».', max_digits=12, verbose_name='cantidad mínima'),
        ),
        migrations.AddIndex(
            model_name='existencia',
            index=models.Index(condition=models.Q(('cantidad_minima__gt', 0)), fields=['negocio'], name='existencia_con_minimo_idx'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_minima__gte', 0)), name='existencia_minima_no_negativa', violation_error_message='La cantidad mínima no puede ser negativa.'),
        ),
    ]
