# Generated by Django 5.2.17 on 2026-09-07 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_crear_movimientos_inventario'),
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('tipo_espacio', models.CharField(choices=[('cerrado', 'Espacio cerrado'), ('aire_libre', 'Al aire libre')], default='cerrado', max_length=20, verbose_name='tipo de espacio')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Vacío mientras el evento no ha terminado.', null=True, verbose_name='fecha de fin')),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('en_curso', 'En curso'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='planeado', max_length=20, verbose_name='estado')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='negocios.negocio', verbose_name='negocio')),
                ('ubicacion', models.ForeignKey(blank=True, help_text='Dónde se monta la barra. Puede definirse después de planear el evento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='inventario.ubicacion', verbose_name='ubicación')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'db_table': 'eventos',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['negocio', 'fecha_inicio'], name='evento_negocio_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gt', models.F('fecha_inicio')), _connector='OR'), name='evento_fechas_coherentes', violation_error_message='El evento no puede terminar antes de empezar.')],
            },
        ),
        migrations.CreateModel(
            name='PulseraNfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('uid_tag', models.CharField(help_text='Número de serie que el chip trae de fábrica. No se escribe: se lee.', max_length=60, verbose_name='UID del chip')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('dañada', 'Dañada'), ('perdida', 'Perdida'), ('retirada', 'Retirada')], default='disponible', help_text='Solo la condición física del chip, no a quién se le prestó.', max_length=20, verbose_name='estado')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pulseras_nfc', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'pulsera NFC',
                'verbose_name_plural': 'pulseras NFC',
                'db_table': 'pulseras_nfc',
                'ordering': ['uid_tag'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'uid_tag'), name='pulsera_uid_unico_por_negocio', violation_error_message='Ese chip ya está registrado en este negocio.')],
            },
        ),
    ]
