# Generated by Django 5.2.17 on 2026-09-08 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_crear_catalogo'),
        ('clientes', '0002_agregar_indice_de_busqueda_por_nombre'),
        ('eventos', '0001_crear_eventos_y_pulseras'),
        ('negocios', '0001_crear_negocios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre_referencia', models.CharField(blank=True, help_text='Cómo lo llama el mesero: "la mesa de los primos".', max_length=100, verbose_name='nombre de referencia')),
                ('mesa_zona', models.CharField(blank=True, max_length=50, verbose_name='mesa o zona')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='estado')),
                ('cerrado_en', models.DateTimeField(blank=True, help_text='Vacío mientras el grupo siga abierto.', null=True, verbose_name='cerrado en')),
                ('abierto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_abiertos', to=settings.AUTH_USER_MODEL, verbose_name='abierto por')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='cerrado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='eventos.evento', verbose_name='evento')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_evento', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'grupo de evento',
                'verbose_name_plural': 'grupos de evento',
                'db_table': 'grupos_evento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ClienteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('limite_alerta', models.DecimalField(blank=True, decimal_places=2, help_text='Monto a partir del cual se avisa. Vacío = sin límite.', max_digits=12, null=True, verbose_name='límite de alerta')),
                ('liberada_en', models.DateTimeField(blank=True, help_text='Vacío = la cuenta sigue abierta.', null=True, verbose_name='liberada en')),
                ('asignada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='asignada por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_evento', to='clientes.cliente', verbose_name='cliente')),
                ('liberada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_liberadas', to=settings.AUTH_USER_MODEL, verbose_name='liberada por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_evento', to='negocios.negocio', verbose_name='negocio')),
                ('pulsera', models.ForeignKey(blank=True, help_text='Vacío = cuenta sin pulsera, se lleva a mano.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='eventos.pulseranfc', verbose_name='pulsera')),
                ('grupo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='eventos.grupoevento', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'cuenta de evento',
                'verbose_name_plural': 'cuentas de evento',
                'db_table': 'clientes_evento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('cliente_evento', models.ForeignKey(blank=True, help_text='Vacío = venta de mostrador: se paga al instante y no hay cuenta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='eventos.clienteevento', verbose_name='cuenta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='eventos.evento', verbose_name='evento')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_evento_tomados', to=settings.AUTH_USER_MODEL, verbose_name='mesero')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_evento', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'pedido de evento',
                'verbose_name_plural': 'pedidos de evento',
                'db_table': 'pedidos_evento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='método de pago')),
                ('referencia_transaccion', models.CharField(blank=True, help_text='Número de aprobación o comprobante. Vacío en los pagos en efectivo.', max_length=100, verbose_name='referencia de la transacción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo se recibió el dinero, que no siempre es cuándo se registró.', verbose_name='fecha')),
                ('cliente_evento', models.ForeignKey(blank=True, help_text='Solo cuando una persona del grupo paga su parte.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='eventos.clienteevento', verbose_name='cuenta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='eventos.evento', verbose_name='evento')),
                ('grupo_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='eventos.grupoevento', verbose_name='grupo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_evento', to='negocios.negocio', verbose_name='negocio')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='recibido por')),
                ('pedido_evento', models.ForeignKey(blank=True, help_text='Solo en la venta de mostrador, que se paga sin abrir cuenta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='eventos.pedidoevento', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pago de evento',
                'verbose_name_plural': 'pagos de evento',
                'db_table': 'pagos_evento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Foto del precio al momento de vender, no el precio de hoy.', max_digits=12, verbose_name='precio unitario')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido_evento', to='negocios.negocio', verbose_name='negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido_evento', to='catalogo.producto', verbose_name='producto')),
                ('pedido_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='eventos.pedidoevento', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'detalle de pedido de evento',
                'verbose_name_plural': 'detalles de pedido de evento',
                'db_table': 'detalle_pedido_evento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlertaConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('monto_acumulado', models.DecimalField(decimal_places=2, help_text='Cuánto llevaba consumido la cuenta cuando saltó la alerta.', max_digits=12, verbose_name='monto acumulado')),
                ('umbral_superado', models.DecimalField(decimal_places=2, help_text='El límite que se cruzó. Se copia para que cambiarlo después no reescriba la historia.', max_digits=12, verbose_name='umbral superado')),
                ('accion_tomada', models.CharField(blank=True, help_text='Vacío mientras la alerta no se atienda.', max_length=200, verbose_name='acción tomada')),
                ('atendida_en', models.DateTimeField(blank=True, help_text='Vacío = sin atender.', null=True, verbose_name='atendida en')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo saltó la alerta.', verbose_name='fecha')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='atendida por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_consumo', to='negocios.negocio', verbose_name='negocio')),
                ('cliente_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='eventos.clienteevento', verbose_name='cuenta')),
            ],
            options={
                'verbose_name': 'alerta de consumo',
                'verbose_name_plural': 'alertas de consumo',
                'db_table': 'alertas_consumo',
                'ordering': ['-fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('atendida_en__isnull', True), ('atendida_por__isnull', True)), models.Q(('atendida_en__isnull', False), ('atendida_por__isnull', False)), _connector='OR'), name='alerta_atencion_coherente', violation_error_message='Al atender una alerta hay que registrar quién la atendió.')],
            },
        ),
        migrations.AddConstraint(
            model_name='clienteevento',
            constraint=models.UniqueConstraint(condition=models.Q(('liberada_en__isnull', True), ('pulsera__isnull', False)), fields=('pulsera',), name='pulsera_con_una_sola_asignacion_activa', violation_error_message='Esa pulsera ya está asignada a una cuenta abierta.'),
        ),
        migrations.AddConstraint(
            model_name='clienteevento',
            constraint=models.CheckConstraint(condition=models.Q(('limite_alerta__isnull', True), ('limite_alerta__gte', 0), _connector='OR'), name='cliente_evento_limite_no_negativo', violation_error_message='El límite de alerta no puede ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='clienteevento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('liberada_en__isnull', True), ('liberada_por__isnull', True)), models.Q(('liberada_en__isnull', False), ('liberada_por__isnull', False)), _connector='OR'), name='cliente_evento_liberacion_coherente', violation_error_message='Al liberar una cuenta hay que registrar quién la liberó.'),
        ),
        migrations.AddConstraint(
            model_name='pagoevento',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_evento_monto_positivo', violation_error_message='El monto de un pago tiene que ser mayor que cero.'),
        ),
        migrations.AddConstraint(
            model_name='pagoevento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo_evento__isnull', False), ('pedido_evento__isnull', True)), models.Q(('cliente_evento__isnull', True), ('grupo_evento__isnull', True), ('pedido_evento__isnull', False)), _connector='OR'), name='pago_evento_tiene_un_solo_destino', violation_error_message='Un pago salda un grupo, la parte de una persona o una venta de mostrador, nunca dos cosas a la vez.'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidoevento',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_evento_cantidad_positiva', violation_error_message='La cantidad debe ser mayor que cero.'),
        ),
        migrations.AddConstraint(
            model_name='detallepedidoevento',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_evento_precio_no_negativo', violation_error_message='El precio no puede ser negativo.'),
        ),
    ]
