# Generated by Django 5.2.17 on 2026-09-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_crear_grupos_cuentas_pedidos_y_pagos'),
        ('inventario', '0003_agregar_cantidad_minima_a_existencias'),
        ('negocios', '0001_crear_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoNfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(help_text='Dónde está puesto: «Puerta principal», «Salida de la terraza».', max_length=100, verbose_name='nombre')),
                ('hash_token', models.CharField(max_length=64, verbose_name='hash del token')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar revoca el token sin perder de qué aparato era.', verbose_name='activo')),
                ('ultimo_uso_en', models.DateTimeField(blank=True, help_text='Vacío mientras no haya consultado nunca. Sirve para ver si sigue vivo.', null=True, verbose_name='último uso')),
            ],
            options={
                'verbose_name': 'dispositivo NFC',
                'verbose_name_plural': 'dispositivos NFC',
                'db_table': 'dispositivos_nfc',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'en_curso'), ('ubicacion__isnull', False)), fields=('ubicacion',), name='evento_una_sola_jornada_en_curso_por_ubicacion', violation_error_message='Esa ubicación ya tiene una jornada abierta.'),
        ),
        migrations.AddField(
            model_name='dispositivonfc',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_nfc', to='negocios.negocio', verbose_name='negocio'),
        ),
        migrations.AddConstraint(
            model_name='dispositivonfc',
            constraint=models.UniqueConstraint(fields=('hash_token',), name='dispositivo_nfc_token_unico', violation_error_message='Ese token ya está en uso.'),
        ),
    ]
