# Generated by Django 5.2.17 on 2026-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
                'db_table': 'negocios',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
