# Generated by Django 5.2.17 on 2026-09-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='negocio',
            table='negocios',
        ),
    ]
